# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudloupe < Formula
  desc "조회 전용 멀티 계정 AWS 리소스 조사 TUI"
  homepage "https://github.com/cnlgks1/cloudloupe"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.1.0/cloudloupe_darwin_amd64.tar.gz"
      sha256 "28e1f44611fa5fec3c7a8ecdd3b466e58ef8f28957ba6b752e2db116dc6f5733"

      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.1.0/cloudloupe_darwin_arm64.tar.gz"
      sha256 "f0ad7453500526439b3ff58d57ceb61c49194d3afb245222222207b84bec1b7d"

      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.1.0/cloudloupe_linux_amd64.tar.gz"
      sha256 "63fcb43b76a03b12347e1955769be6144d5ce0c4557d054850383a79becd8c86"
      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.1.0/cloudloupe_linux_arm64.tar.gz"
      sha256 "93bc66a2be9c1e7f0b79fa27ce784cddd177adbbe25ffc21492dd5cce235ada9"
      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
  end

  test do
    system "#{bin}/cloudloupe", "--version"
  end
end
