# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudloupe < Formula
  desc "조회 전용 멀티 계정 AWS 리소스 조사 TUI"
  homepage "https://github.com/cnlgks1/cloudloupe"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.0.1/cloudloupe_darwin_amd64.tar.gz"
      sha256 "281c7e09b97b07358f27101f6252a84b46d0d7d6576c04ff885995853a621c5e"

      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.0.1/cloudloupe_darwin_arm64.tar.gz"
      sha256 "ef7af2a58d4272beee3116911ce733a6702e45d6ebb32b02ae9390f4b4c43f0d"

      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.0.1/cloudloupe_linux_amd64.tar.gz"
      sha256 "84c05c743fd2a809935cbed9b15c436aad1b4262874c2c24cd269c478863dda7"
      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnlgks1/cloudloupe/releases/download/v1.0.1/cloudloupe_linux_arm64.tar.gz"
      sha256 "e6c3d14b7ab0f6858a358961d16e8feb1c899270a7c0996dbe54453a56414b93"
      define_method(:install) do
        bin.install "cloudloupe"
      end
    end
  end

  test do
    system "#{bin}/cloudloupe", "--version"
  end
end
